name: Sync Fork

on:
  schedule:
    - cron: '0 21 * * *' # every 30 minutes
  workflow_dispatch: # on button click

jobs:
  sync:

    runs-on: ubuntu-latest

    steps:
      - uses: tgymnich/fork-sync@v2.0.9
        with:
          owner: PizazzGY
          repo: TVBox
          head: main
          base: main
          ignore_fail: true
